### ISSUE TITLE
Bug: Error message by Google OAuth when logging in: "Google has not verified this application"

### ISSUE THREAD

**Issue by pataquets** [DarthBenro008/rchore#21]
Dowloaded binary, ran `rchore google login`, pasted URL into browser.
After selecting my personal Google Account to continue, a warning (with a big, ugly, red :warning: sign) message as the above appears (albeit in my language). The message also states that "until the author has not verified this app with Google, you should not use it.".

If you click the advanced options, you can still proceed, but this looks very scary, nonetheless.

**Comment by DarthBenro008** [comment]
Hi @pataquets, please refer to https://github.com/DarthBenro008/rchore/issues/15#issuecomment-905144712

Unfortunately app verification costs money with strict restrictions, hence there is no other way to bypass the scary message :(


Due to it not being a bug, i am closing the issue, do feel free to reopen if you have any other ideas in mind! 😃

**Comment by pataquets** [comment]
Oh, didn't knew that, @DarthBenro008, thanks for the quick response. Fair enough. Sorry to bother you.
However, to consider this truly closed, some explanatory message in the docs or, even better, on screeen could be shown warning the user as this is to be expected, maybe even linking here, so nobody freaks out again :smile:

**Comment by DarthBenro008** [comment]
@pataquets opened a new issue with better outlining in #23 😃

**Comment by pataquets** [comment]
Very thoughtful on your part. Thank you.
